version: '3'
services:
  db:
    image: 'postgres:latest' 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  app:
      container_name: orders-api
      restart: always
      build: .
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
          - "3000:3000"
      depends_on:
          - db